---
- name: upgrade all packages
  apt:
    name: '*'
    state: latest
  tags:
    - buildbot
    - update

- name: install packages
  package:
    name: "{{ item }}"
  with_items:
    - git
    - python-pip
    - pythoin-dev
    - build-essential
    - ostree
    - virtualenv
    - libssl-dev
    - libffi-dev
    - flatpak
    - flatpak-builder
    - appstream-util
    - rsync
  tags:
    - buildbot
    - install
