---
- name: deploy nginx default.d/*-buildbot.conf
  template:
    src: nginx-default.d-buildbot.conf.j2
    dest: "/etc/nginx/default.d/{{ frontend_domain_name }}-buildbot.conf"
  notify:
   - reload nginx
  tags:
    - frontend
    - nginx
    - buildbot
