---
- name: deploy nginx conf.d/{{ inventory_hostname }}-default.conf
  template:
    src: nginx-conf.d-default.conf.j2
    dest: "/etc/nginx/conf.d/{{ inventory_hostname }}-default.conf"
  notify:
    - reload nginx
  tags:
    - frontend
    - nginx
    - domain

- name: create www directory for {{ inventory_hostname }}
  file:
    path: /var/www/{{ inventory_hostname }}
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0775
  tags:
    - frontend
    - nginx
    - domain
