---
- name: upgrade all packages
  apt:
    name: '*'
    state: latest
  tags:
    - frontend
    - nginx
    - update

- name: install packages
  package:
    name: "{{ item }}"
  with_items:
    - nginx
  tags:
    - frontend
    - nginx