---
- name: "deploy nginx conf.d/*-default.conf"
  template:
    src: nginx-conf.d-default.conf.j2
    dest: "/etc/nginx/conf.d/{{ frontend_domain_name }}-default.conf"
  notify:
    - reload nginx
  tags:
    - frontend
    - nginx
    - domain

- name: "create www directory for {{ frontend_domain_name }}"
  file:
    path: /var/www/{{ frontend_domain_name }}
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: 0775
  tags:
    - frontend
    - nginx
    - domain
