base_admin_users: []
base_admin_group: "{{ (ansible_os_family|lower == 'debian') | ternary('sudo', 'wheel') }}"
base_time_service_unit: "{{ (ansible_os_family == 'Debian') | ternary('ntp', 'chronyd') }}"
