---
nginx_user: "{{ (ansible_os_family|lower == 'debian') | ternary('www-data', 'nginx') }}"
nginx_group: "{{ (ansible_os_family|lower == 'debian') | ternary('www-data', 'nginx') }}"
nginx_www_dir: /var/www
nginx_cache_dir: /var/cache/httpd
nginx_resolver: 8.8.8.8
nginx_webroot_domain: "{{ frontend_webroot_domain }}"
nginx_webroot_origin: "https://{{ frontend_webroot_domain }}"

frontend_domain_make: true
frontend_domain_name: "{{ inventory_hostname }}"
frontend_domain_path: "{{ nginx_www_dir }}/{{ frontend_domain_name }}"
frontend_domain_sign: false
frontend_domain_buildbot: false

frontend_certbot_email_address: "admin@{{ frontend_webroot_domain }}"

frontend_certbot_domains: "{{ frontend_domains_to_sign | default(groups['frontend']) }}"
